### ISSUE TITLE
Unreal 5.1 Support?

### ISSUE THREAD

**Issue by nickknyc** [microsoft/MixedReality-UXTools-Unreal#67]
Looking forward to it.

**Comment by luis-valverde-ms** [comment]
@nickknyc , we have beta support in the [public/0.12.x-UE5.1](https://github.com/microsoft/MixedReality-UXTools-Unreal/tree/public/0.12.x-UE5.1) branch. It's beta because it hasn't gone through our QA process yet. See here for the list of changes and a few caveats: #66

**Comment by nickknyc** [comment]
many thanks Luis and team

Nick

Sent from Surface Duo 2
________________________________

**Comment by travis-rothbloom** [comment]
> @nickknyc , we have beta support in the [public/0.12.x-UE5.1](https://github.com/microsoft/MixedReality-UXTools-Unreal/tree/public/0.12.x-UE5.1) branch. It's beta because it hasn't gone through our QA process yet. See here for the list of changes and a few caveats: #66

Is there any update to this? The UXTools-0.12.1-5.1.zip file on the Releases page is only 10MB while the equivalent zip file for version 5.0 is 291MB, was this just not packaged properly on there? When I try to attach this to a UE5.1 project, I get the error below:

"The following modules are missing or built with a different engine version:

UXTools
UXToolsEditor
UXToolsInput
UXToolsShaders
XRSimulation
XRSimulationEditor
XRSimulationInput

Engine modules cannot be compiled at runtime. Please build through our IDE."

**Comment by Abhishek21296** [comment]
> @nickknyc , we have beta support in the [public/0.12.x-UE5.1](https://github.com/microsoft/MixedReality-UXTools-Unreal/tree/public/0.12.x-UE5.1) branch. It's beta because it hasn't gone through our QA process yet. See here for the list of changes and a few caveats: #66

Any update on this? Not able to import the plugin in UE5.1.

**Comment by Bortronx** [comment]
@travis-rothbloom  fieldsJacksonG fork works see https://github.com/fieldsJacksonG/MixedReality-UXTools-Unreal 
The latest commit is a pull request and it won't show up when you try to clone the branch.

**Comment by Kean4711DUB** [comment]
Try to follow this video and it should take care of the missing modules if you are using the older versions. https://www.youtube.com/watch?v=2HHJ6AYnwFw&t=298s

**Comment by luis-valverde-ms** [comment]
Sorry for the lack of news. We haven't been able to spend time working on this and I don't think we will be able to in the next few months either.

**Comment by Bortronx** [comment]
> Sorry for the lack of news. We haven't been able to spend time working on this and I don't think we will be able to in the next few months either. 

Will you be able to accept pull requests or let someone accept them?

**Comment by luis-valverde-ms** [comment]
If it is a straightforward change to unblock this, we will find the time to review and merge. Other than that, we won't be able to spend time reviewing contributions. I'll investigate if we can open the repo for others to contribute directly.

**Comment by Abhishek21296** [comment]
Any update on this?

**Comment by luis-valverde-ms** [comment]
Sorry @Abhishek21296 , no news yet. We're still working on figuring out the longer term plan for UX Tools support.

**Comment by Abhishek21296** [comment]
Atleast do us a favor and get the epic store updated to say that this is not working in 5.1! At the moment the store page says its supported in 5.1 .

**Comment by Deltajom** [comment]
Just tried recompiling using RunUAT.bat from the 5.1.0 release mentioned by [luis-valverde-ms](https://github.com/luis-valverde-ms) above to 5.1.1 release and get the following errors in both Android and HoloLens 2 compilations. 

```
[3/12] Compile Module.UXTools.3_of_8.cpp
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\UXTools\Public\Input\UxtHandInteractionActor.h(128): error C2065: 'FOverlapResult': undeclared identifier
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\UXTools\Public\Input\UxtHandInteractionActor.h(128): error C2923: 'TArray': 'FOverlapResult' is not a valid template type argument for parameter 'InElementType'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\UXTools\Public\Input\UxtHandInteractionActor.h(128): note: see declaration of 'FOverlapResult'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\UXTools\Public\Input\UxtHandInteractionActor.h(128): error C2976: 'TArray': too few template arguments
D:\UnrealEngines\UE_5.1\Engine\Source\Runtime\Core\Public\Containers\Array.h(351): note: see declaration of 'TArray'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\UXTools\Public\Input\UxtHandInteractionActor.h(128): error C2955: 'TArray': use of class template requires template argument list
D:\UnrealEngines\UE_5.1\Engine\Source\Runtime\Core\Public\Containers\Array.h(351): note: see declaration of 'TArray'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\UXTools\Public\Input\UxtHandInteractionActor.h(128): error C2955: 'TArray': use of class template requires template argument list
D:\UnrealEngines\UE_5.1\Engine\Source\Runtime\Core\Public\Containers\Array.h(351): note: see declaration of 'TArray'
[4/12] Compile Module.UXTools.7_of_8.cpp
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\UXTools\Public\Tooltips\UxtTooltipSpawnerComponent.h(160): error C2065: 'UUserWidget': undeclared identifier
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\UXTools\Public\Tooltips\UxtTooltipSpawnerComponent.h(160): error C2923: 'TSubclassOf': 'UUserWidget' is not a valid template type argument for parameter 'TClass'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\UXTools\Public\Tooltips\UxtTooltipSpawnerComponent.h(160): note: see declaration of 'UUserWidget'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\UXTools\Public\Tooltips\UxtTooltipSpawnerComponent.h(160): error C3000: 'TSubclassOf': use of class template requires template argument list. Argument deduction is not allowed in non-static data member
D:\UnrealEngines\UE_5.1\Engine\Source\Runtime\CoreUObject\Public\Templates\SubclassOf.h(23): note: see declaration of 'TSubclassOf'
```
I also tried a recompile from the main 5.0 branch and got different issues. 

```
[24/40] Compile Module.XRSimulation.cpp
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Public\XRSimulationHMD.h(106): error C3668: 'FXRSimulationHMD::RenderTexture_RenderThread': method with override specifier 'override' did not override any base class methods
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Public\XRSimulationHMD.h(106): warning C4263: 'void FXRSimulationHMD::RenderTexture_RenderThread(FRHICommandListImmediate &,FRHITexture2D *,FRHITexture2D *,FVector2D) const': member function does not override any base class virtual member function
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Public\XRSimulationHMD.h(167): warning C4264: 'void IStereoRendering::RenderTexture_RenderThread(FRHICommandListImmediate &,FRHITexture *,FRHITexture *,FVector2D) const': no override available for virtual member function from base 'IStereoRendering'; function is hidden
D:\UnrealEngines\UE_5.1\Engine\Source\Runtime\Engine\Public\StereoRendering.h(169): note: see declaration of 'IStereoRendering::RenderTexture_RenderThread'
D:\UnrealEngines\UE_5.1\Engine\Source\Runtime\Engine\Classes\Engine\Engine.h(44): note: see declaration of 'IStereoRendering'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(257): error C2511: 'void FXRSimulationHMD::CopyTexture_RenderThread(FRHICommandListImmediate &,FRHITexture2D *,FIntRect,FRHITexture2D *,FIntRect,bool,bool) const': overloaded member function not found in 'FXRSimulationHMD'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Public\XRSimulationHMD.h(26): note: see declaration of 'FXRSimulationHMD'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(267): error C2027: use of undefined type 'FRHITexture2D'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Public\XRSimulationHMD.h(107): note: see declaration of 'FRHITexture2D'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(267): error C2737: 'SrcTextureWidth': const object must be initialized
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(268): error C2027: use of undefined type 'FRHITexture2D'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Public\XRSimulationHMD.h(107): note: see declaration of 'FRHITexture2D'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(268): error C2737: 'SrcTextureHeight': const object must be initialized
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(278): error C2027: use of undefined type 'FRHITexture2D'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Public\XRSimulationHMD.h(107): note: see declaration of 'FRHITexture2D'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(284): error C2027: use of undefined type 'FRHITexture2D'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Public\XRSimulationHMD.h(107): note: see declaration of 'FRHITexture2D'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(313): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'FRHITransitionInfo'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(313): note: No constructor could take the source type, or constructor overload resolution was ambiguous
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(318): error C2665: 'FScreenPS::SetParameters': none of the 2 overloads could convert all the argument types
D:\UnrealEngines\UE_5.1\Engine\Source\Runtime\Engine\Public\ScreenRendering.h(83): note: could be 'void FScreenPS::SetParameters(FRHICommandList &,FRHISamplerState *,FRHITexture *)'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(318): note: 'void FScreenPS::SetParameters(FRHICommandList &,FRHISamplerState *,FRHITexture *)': cannot convert argument 3 from 'FRHITexture2D *' to 'FRHITexture *'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(318): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
D:\UnrealEngines\UE_5.1\Engine\Source\Runtime\Engine\Public\ScreenRendering.h(83): note: see declaration of 'FScreenPS::SetParameters'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(318): note: while trying to match the argument list '(FRHICommandListImmediate, RHIParamRefType, FRHITexture2D *)'
        with
        [
            RHIParamRefType=FRHISamplerState *
        ]
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(322): error C2665: 'FScreenPS::SetParameters': none of the 2 overloads could convert all the argument types
D:\UnrealEngines\UE_5.1\Engine\Source\Runtime\Engine\Public\ScreenRendering.h(83): note: could be 'void FScreenPS::SetParameters(FRHICommandList &,FRHISamplerState *,FRHITexture *)'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(322): note: 'void FScreenPS::SetParameters(FRHICommandList &,FRHISamplerState *,FRHITexture *)': cannot convert argument 3 from 'FRHITexture2D *' to 'FRHITexture *'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(322): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
D:\UnrealEngines\UE_5.1\Engine\Source\Runtime\Engine\Public\ScreenRendering.h(83): note: see declaration of 'FScreenPS::SetParameters'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(322): note: while trying to match the argument list '(FRHICommandListImmediate, RHIParamRefType, FRHITexture2D *)'
        with
        [
            RHIParamRefType=FRHISamplerState *
        ]
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(479): error C2664: 'void FDefaultSpectatorScreenController::RenderSpectatorScreen_RenderThread(FRHICommandListImmediate &,FRHITexture2D *,FTexture2DRHIRef,FVector2D)': cannot convert argument 2 from 'FRHITexture2D *' to 'FRHITexture2D *'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Private\XRSimulationHMD.cpp(479): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
D:\UnrealEngines\UE_5.1\Engine\Source\Runtime\HeadMountedDisplay\Public\DefaultSpectatorScreenController.h(36): note: see declaration of 'FDefaultSpectatorScreenController::RenderSpectatorScreen_RenderThread'
[25/40] Link UnrealEditor-XRSimulation.lib cancelled
[26/40] Link UnrealEditor-XRSimulation.dll cancelled
[27/40] Link UnrealEditor-XRSimulationEditor.dll cancelled
[28/40] Compile SharedPCH.Engine.ShadowErrors.cpp
[29/40] Compile Module.UXTools.8_of_8.cpp
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\UXTools\Private\Controls\UxtToggleGroupComponent.cpp(123): error C2440: '=': cannot convert from 'TWeakObjectPtr<AActor,FWeakObjectPtr>' to 'AActor *'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\UXTools\Private\Controls\UxtToggleGroupComponent.cpp(123): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\UXTools\Private\Utils\UxtFunctionLibrary.cpp(67): error C2440: '?': cannot convert from 'const TWeakObjectPtr<AActor,FWeakObjectPtr>' to 'bool'
D:\UnrealEngines\UE_5.1\Engine\Build\BatchFiles>
e operator cannot be called
[30/40] Compile Module.XRSimulationInput.cpp
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Public\XRSimulationHMD.h(106): error C3668: 'FXRSimulationHMD::RenderTexture_RenderThread': method with override specifier 'override' did not override any base class methods
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Public\XRSimulationHMD.h(106): warning C4263: 'void FXRSimulationHMD::RenderTexture_RenderThread(FRHICommandListImmediate &,FRHITexture2D *,FRHITexture2D *,FVector2D) const': member function does not override any base class virtual member function
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulation\Public\XRSimulationHMD.h(167): warning C4264: 'void IStereoRendering::RenderTexture_RenderThread(FRHICommandListImmediate &,FRHITexture *,FRHITexture *,FVector2D) const': no override available for virtual member function from base 'IStereoRendering'; function is hidden
D:\UnrealEngines\UE_5.1\Engine\Source\Runtime\Engine\Public\StereoRendering.h(169): note: see declaration of 'IStereoRendering::RenderTexture_RenderThread'
D:\UnrealEngines\UE_5.1\Engine\Source\Runtime\Engine\Classes\Engine\Engine.h(44): note: see declaration of 'IStereoRendering'
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulationInput\Private\XRSimulationInputDevice.cpp(49): warning C4996: 'FGenericApplicationMessageHandler::OnControllerButtonPressed': This version of OnControllerButtonPressed has been deprecated, please use the one that takes an FPlatformUser and FInputDeviceId instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulationInput\Private\XRSimulationInputDevice.cpp(54): warning C4996: 'FGenericApplicationMessageHandler::OnControllerButtonReleased': This version of OnControllerButtonReleased has been deprecated, please use the one that takes an FPlatformUser and FInputDeviceId instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulationInput\Private\XRSimulationInputDevice.cpp(60): warning C4996: 'FGenericApplicationMessageHandler::OnControllerButtonPressed': This version of OnControllerButtonPressed has been deprecated, please use the one that takes an FPlatformUser and FInputDeviceId instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\UE5Games\TempPluginsHolder\UE5p1p1UXToolsBetaRecompile\HostProject\Plugins\UXTools\Source\XRSimulationInput\Private\XRSimulationInputDevice.cpp(65): warning C4996: 'FGenericApplicationMessageHandler::OnControllerButtonReleased': This version of OnControllerButtonReleased has been deprecated, please use the one that takes an FPlatformUser and FInputDeviceId instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
```

Compiling from 5.1.0 looks to be a better bet for now, might just try removing the offending features for now to see if it will work. 

If anyone has suggestions let me know! I'm working on this for my thesis, and really don't want to fall back to my 5.0.2 app.

**Comment by Abhishek21296** [comment]
@Deltajom I tried building from 5.0 to 5.1 and imported that in 5.1.1, My build seems to be working fine in hololens 2. Followed the same video above. (Though you might want to exit the incredibuild if its present in your tray)

**Comment by Deltajom** [comment]
Ok so UE 5.1.1's RunUAT.bat was still failing for me, but if I put the 5.1.0 beta release in a Plugins folder local to the project instead of the Marketplace Plugins folder, and re-compile through when prompted when starting the project up it works. @Abhishek21296 Thank you for the quick response, I did also exit incredibuild as well before trying this, so that may also be needed.

**Comment by luis-valverde-ms** [comment]
> Atleast do us a favor and get the epic store updated to say that this is not working in 5.1! At the moment the store page says its supported in 5.1 .

@Abhishek21296 , good idea. I removed 5.1 support from the store and from the GitHub release page. I think the dev working on it was eager to share it with the community early but seems to be causing more trouble than helping.

**Comment by nickknyc** [comment]
Well, might as well start working on 5.2 as well ;^)

Thanks for all the efforts!!

Nick

**Comment by ChaosRer** [comment]
When will 5.1 be supported? GraphicsTools already supports 5.1
